export const FlightActionTypes = {
    UPDATE_ROTATION_LIST: 'UPDATE_ROTATION_LIST',
    REMOVE_FROM_ROTATION_LIST: 'REMOVE_FROM_ROTATION_LIST',
    UPDATE_UTILIZATION_PERCENTAGE: 'UPDATE_UTILIZATION_PERCENTAGE',
    SET_AIRCRAFT_DATA: 'SET_AIRCRAFT_DATA',
    SET_FLIGHT_DATA: 'SET_FLIGHT_DATA',
    SET_PAGE_OFFSET: 'SET_PAGE_OFFSET'
} 